---
# All phabricator config values
- name: configure db credentials
  command: "{{ web_root }}/phabricator/bin/config set mysql.{{ item.key }} '{{ item.value }}'"
  with_dict: "{{ database_config }}"
  changed_when: False

- name: run phabricator db migrations
  command: "{{ web_root }}/phabricator/bin/storage upgrade --force"
  changed_when: False

- name: configure base URI
  command: "{{ web_root }}/phabricator/bin/config set phabricator.base-uri '{{ protocol }}://{{ server_url }}/'"
  changed_when: False

- name: set daemon user
  command: "{{ web_root }}/phabricator/bin/config set phd.user '{{ users.daemon }}'"
  changed_when: False

- name: set vcs user
  command: "{{ web_root }}/phabricator/bin/config set diffusion.ssh-user '{{ users.vcs }}'"
  changed_when: False

- name: set http auth
  command: "{{ web_root }}/phabricator/bin/config set diffusion.allow-http-auth '{{ allow_http_auth }}'"
  changed_when: False

- name: configue pygments highlighting
  command: "{{ web_root }}/phabricator/bin/config set pygments.enabled 'true'"
  changed_when: False

- name: auth email domains
  command: "{{ web_root }}/phabricator/bin/config set auth.email-domains '{{ phabricator_auth_email_domains }}'"
  changed_when: False
  when: not((phabricator_auth_email_domains is undefined) or (phabricator_auth_email_domains is none) or (phabricator_auth_email_domains|trim == ''))

- name: file storage
  command: "{{ web_root }}/phabricator/bin/config set storage.local-disk.path '{{ phabricator_local_disk_path }}'"
  changed_when: False
  when: phabricator_file_storage == "local"

- name: set metamta.default-address 
  command: "{{ web_root }}/phabricator/bin/config set metamta.default-address '{{ phabricator_metamta_default_address }}'"
  changed_when: False
  when: not((phabricator_metamta_default_address is undefined) or (phabricator_metamta_default_address is none) or (phabricator_metamta_default_address|trim == ''))

- name: set metamta.domain
  command: "{{ web_root }}/phabricator/bin/config set metamta.domain '{{ phabricator_metamta_domain }}'"
  changed_when: False
  when: not((phabricator_metamta_domain is undefined) or (phabricator_metamta_domain is none) or (phabricator_metamta_domain|trim == ''))
