---
- name: install packages for mysql (Debian)
  apt:
    name: "{{ phabricator_packages_local }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: install packages for mysql RHEL
  yum:
    name: "{{ phabricator_packages_local }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

# - name: check services
#   shell: systemctl
#   register: systemctloutput
# 
# - name: print service output
#   debug: var=systemctloutput.stdout_lines

- name: start mysql
  service:
    name: "{{ mysql_service }}"
    state: started

# if you don't have (Python 2.7 and Python 3.X), then this should be installed
# - name: install required python module
#   pip:
#     name: MySQL-python

- name: install required python module
  pip:
    name: PyMySQL
  become: false
  changed_when: false

- name: create mysql user
  mysql_user:
    login_unix_socket: "{{ mysql_socket }}"
    name: "{{ database_config.user }}"
    password: "{{ database_config.pass }}"
    priv: "*.*:ALL,GRANT"
    state: present

# Put SELinux in permissive mode, logging actions that would be blocked.
- name: permissive selinux
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"
  ignore_errors: true
