---
- name: install packages for mysql (Debian)
  apt:
    name: "{{ phabricator_packages_local }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install packages for mysql RHEL
  yum:
    name: "{{ phabricator_packages_local }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: start mysql
  service:
    name: "{{ mysql_service }}"
    state: started

- name: install required python module
  pip:
    name: MySQL-python

- name: create mysql user
  mysql_user:
    name: "{{ database_config.user }}"
    password: "{{ database_config.pass }}"
    priv: "*.*:ALL,GRANT"
    state: present

# Put SELinux in permissive mode, logging actions that would be blocked.
- name: permissive selinux
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"
  ignore_errors: yes
