---
# handlers file for phabricator
- name: restart nginx
  service:
    name: nginx
    state: restarted

#note github issue 19898
- name: restart php-fpm
  service:
    name: "{{ php_service }}"
    state: restarted

- name: restart mysql
  service:
    name: "{{ mysql_service }}"
    state: restarted

- name: restart exim
  service:
    name: "{{ exim_service_name }}"
    state: restarted

- name: restart upstart phabricator-phd
  service: state=restarted name=phabricator-phd 

- name: restart systemd phabricator-phd
  systemd: state=restarted name=phabricator-phd daemon_reload=yes
