---
# handlers file for phabricator
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: restart upstart phd
  service: state=restarted name=phabricator-phd 

- name: restart systemd phd
  systemd: state=started name=phabricator-phd daemon_reload=yes
