---
# handlers file for phabricator
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

#note github issue 19898
- name: restart php-fpm
  service:
    name: "{{ php_service }}"
    state: restarted
    enabled: yes

- name: restart upstart phabricator-phd
  service:
    name: phabricator-phd
    state: restarted
    enabled: yes

- name: restart systemd phabricator-phd
  systemd:
    name: phabricator-phd
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart mysql
  service:
    name: "{{ mysql_service }}"
    state: restarted
    enabled: yes

- name: restart exim
  service:
    name: "{{ exim_service_name }}"
    state: restarted
    enabled: yes
